### ISSUE TITLE
 Not able to create a conda environment with the ```requirements.txt``` file

### ISSUE THREAD

**Issue by camiloramirezgo** [KTH-dESA/unescap#11]
When ```conda``` installing with  ```conda install -c conda-forge --file requirements.txt```  I get this error:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - snakemake
```
I also tried ```conda create -n unescap -c bioconda -c conda-forge --file requirements.txt```, but got incompatibility among packages:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:
```
The list is very long, but I noticed that ```snakemake``` was in there, thus I removed the ```snakemake``` package from the requirements list and the environment was created successfully.

This makes me wonder if we should have a separate ```requirements.txt``` file for the dashboard, or just should we remove the ```snakemake``` package from the file?

**Comment by willu47** [comment]
You can remove snakemake, or pin python to version 3.6 in the call to conda. E.g. 
```
conda create -n env -c bioconda -c conda-forge python=3.6 --file requirements.txt
```
