### ISSUE TITLE
SDG7.1.2 - remove solar thermal and add biomass

### ISSUE THREAD

**Issue by FraGard** [KTH-dESA/unescap#26]
@camiloramirezgo let me know what needs changing. Solar thermal not used for cooking. While biomass must be shown, to see that it goes to 0 by 2030 to meet SDG7.1.2

**Comment by camiloramirezgo** [comment]
Hi @FraGard, first make sure that the biomass technology is in the `Cooking.xlsx` file. I think it is not there, so the app is not looking for it in the results files. You need to add then the biomass technology to that file. 

About the solar thermal not being used, are you sure osemosys is not selecting solar thermal for cooking? in the `Cooking.xlsx` file there is a technology called `RES_CWH_SOLAR`, if this one is not related to cooking then it should be removed from that file.
