### ISSUE TITLE
Under TFEC add AnnualEmissions of CO2

### ISSUE THREAD

**Issue by FraGard** [KTH-dESA/unescap#28]
Let us show a global figure of CO2 emissions by the entire energy sector, to show if and how the unconditional NDC target is met

**Comment by camiloramirezgo** [comment]
@FraGard if this global CO2 emissions figure is only for the energy sector (power generation) then it is already in the `Electricity supply and demand` block:

![image](https://user-images.githubusercontent.com/12953752/66299816-8acf0c80-e8f4-11e9-871d-194d0527a745.png)

However, if what is needed are the CO2 emissions for the TFEC then that one is missing and can be added.

**Comment by FraGard** [comment]
The one there is only for electricity generation. One for the entire energy sector (i.e. for the TFEC, including residential, commerce, other, industry, transportation) should be added. For that, it is sufficient to take either the 'AnnualEmissions' csv or all CO2 emissions from the 'AnnualTechnologyEmissions'. Probably, the latter is faster, as the files are already there. But let me know which one is best and how I can help.
