### ISSUE TITLE
Electricity generation by type and source not working

### ISSUE THREAD

**Issue by FraGard** [KTH-dESA/unescap#36]
Under the tag ' electricity supply and demand', when choosing the graph of electricity generation and the scenario, nothing changes between sorting by 'type' and by 'source'. One should be showing generation by technology type (e.g. coal pp, ocgt, ccgt, hydro, etc.). Another one by fuel, I think, but not necessary...

**Comment by camiloramirezgo** [comment]
I don't really get what you mean, as when I select by source I get this:

![image](https://user-images.githubusercontent.com/12953752/67005739-9637ea00-f0e3-11e9-87d4-c1f3e9a251d9.png)

And when select by type this:

![image](https://user-images.githubusercontent.com/12953752/67005779-af409b00-f0e3-11e9-8deb-e812caf95253.png)

The first is showing the source of generation of the electricity, as solar, wind, diesel, etc. and the second the type of source fossil fuel or renewable. I can change this of course, in the `Electricity_generation.xlsx` file, we just need to change the data from the `Source` and the `Type` columns, to whatever we want to show in each graph.

**Comment by FraGard** [comment]
It was properly working
