### ISSUE TITLE
Show economic parameters

### ISSUE THREAD

**Issue by FraGard** [KTH-dESA/unescap#37]
In the TFEC visual, above the graphs, include text box to show:

- NPV (Net Present Value) of the total system cost for each scenario (in M$);
- Saves in subsidies for each scenario (in M$);

I would write, e.g.:

'NPV of the total system cost: ........ M$' [somehow big and in bold characters, with no decimals]

I will provide under each scenario subfolder an excel (or .csv?) file with the two values in it, NPV on top and saves in subsidies below.

**Comment by camiloramirezgo** [comment]
Hi @FraGard, that is good. The excel filo or .csv are ok, choose the one you like most ;)
