### ISSUE TITLE
Electricity for residential sector is divided in three different parts

### ISSUE THREAD

**Issue by camiloramirezgo** [KTH-dESA/unescap#5]
In the visualisation for the electricity supply and demand, when filter by use is selected the electricity for appliances appears divided in two different parts for the BAU and Current Policies scenarios and three parts for the SDG scenario:
![image](https://user-images.githubusercontent.com/12953752/64939527-94b79f80-d861-11e9-87b0-bd5b2294983a.png)
This is due to how the use column is defined in the ```Electricity_demand.xlsx``` file:
![image](https://user-images.githubusercontent.com/12953752/64939614-d8aaa480-d861-11e9-8b35-0589beb0db0f.png)
By making those three uses match the problem would be fixed.

Is there a reason for these to be defined that way?

**Comment by FraGard** [comment]
they are separate in the model and yes there's a reason for them to be separate. any practical way this can be fixed without changing the model?

**Comment by camiloramirezgo** [comment]
Yes, if we want to just add them together for the visualisation, it would be just to write the same name for the three of them in the use column of the ```Electricity_demand.xslx```. So no need a all to change anything in the model, this one is a really easy fix, I will do it right now.
