### ISSUE TITLE
Add option to change units of visualisation

### ISSUE THREAD

**Issue by camiloramirezgo** [KTH-dESA/unescap#6]
Add options for the user to be able to choose the units of visualisation. This would be:
* For energy: Pj, Mtoe and boe.
* For electricity: TWh, any other?

This can be done as:
* A separate menu like a settings or units menu, where the user can select the overall units for energy and electricity. This settings would be applied to all the visualisations, or
* An individual option withing each graph so the user can select individually the units for each visualisation. (of course this one requires more work, but it is feasible)

**Comment by FraGard** [comment]
correct on the units. regarding the method, I would go for the 1st one
